#등급이 표시되는 형식
rank-format: "§l§9등급: %s"
#조합시에 예상 등급이 표시되는 형식
maybe-format: §l§9랜덤적용
#공격력이 표시되는 형식
attack-damage-format: §d공격력 +%s
#공격 속도가 표시되는 형식
attack-speed-format: §d공격 속도 +%s
#채굴 속도가 표시되는 형식
mining-speed-format: §9채굴 속도 +%s

#등급과 그에 해당하는 값
ranks:
  §dS: 6
  §aA: 4
  §6B: 2
  §eC: 1

items:
  diamond_sword:
    generic.attackDamage:
      mean: 4
      bonus-by-rank: 0.65
      #랜덤값의 표준편차
      standard-deviation: 0.43
      #정규분포의 하한값과 평균의 차
      lower-bound-from-mean: 0.5
      #정규분포의 상한값과 평균의 차
      upper-bound-from-mean: 0.51
  iron_sword:
    generic.attackDamage:
      mean: 2.9
      bonus-by-rank: 0.42
      standard-deviation: 0.3
      lower-bound-from-mean: 0.5
      upper-bound-from-mean: 0.49

  diamond_axe:
    generic.attackDamage:
      mean: 8.5
      bonus-by-rank: 1.8
      standard-deviation: 1.35
      lower-bound-from-mean: 1.5
      upper-bound-from-mean: 1.55
  iron_axe:
    generic.attackDamage:
      mean: 6.3
      bonus-by-rank: 1.15
      standard-deviation: 1.3
      lower-bound-from-mean: 1.53
      upper-bound-from-mean: 1.53

  diamond_pickaxe:
    miningSpeed:
      mean: 2.0
      bonus-by-rank: 1.5
      standard-deviation: 1.1
      lower-bound-from-mean: 4
      upper-bound-from-mean: 4.1
  iron_pickaxe:
    miningSpeed:
      mean: 0
      bonus-by-rank: 0.9
      standard-deviation: 1
      lower-bound-from-mean: 3.9
      upper-bound-from-mean: 4

  diamond_chestplate:
    generic.armor:
      mean: 9.0
      bonus-by-rank: 2.2
      standard-deviation: 2
      lower-bound-from-mean: 4.1
      upper-bound-from-mean: 4.1
  iron_chestplate:
    generic.armor:
      mean: 6.0
      bonus-by-rank: 1.5
      standard-deviation: 2
      lower-bound-from-mean: 3.9
      upper-bound-from-mean: 3.9